In [ ]:
!pip install qutip

In [ ]:
!pip install krotov

In [ ]:
import sys
import os
import qutip
import numpy as np
import scipy
import matplotlib
import matplotlib.pylab as plt
import krotov
from scipy.fftpack import fft
from scipy.interpolate import interp1d
from qutip.control import *

from scipy.stats import unitary_group
import math as mt

In [ ]:

zIsigma_z= np.array([[1, 0, 0, 0, 0, 0, 0, 0],
           [0, -1, 0, 0, 0, 0, 0, 0],
           [0, 0, 1, 0, 0, 0, 0, 0],
           [0, 0, 0, -1, 0, 0, 0, 0],
           [0, 0, 0, 0, -1, 0, 0, 0],
           [0, 0, 0, 0, 0, 1, 0, 0],
           [0, 0, 0, 0, 0, 0, -1, 0],
           [0, 0, 0, 0, 0, 0, 0, 1]])
zsigma_zI= np.array([[1, 0, 0, 0, 0, 0, 0, 0],
           [0, 1, 0, 0, 0, 0, 0, 0],
           [0, 0, -1, 0, 0, 0, 0, 0],
           [0, 0, 0, -1, 0, 0, 0, 0],
           [0, 0, 0, 0, -1, 0, 0, 0],
           [0, 0, 0, 0, 0, -1, 0, 0],
           [0, 0, 0, 0, 0, 0, 1, 0],
           [0, 0, 0, 0, 0, 0, 0, 1]])

IIsigma_z= np.array([[1, 0, 0, 0, 0, 0, 0, 0],
           [0, -1, 0, 0, 0, 0, 0, 0],
           [0, 0, 1, 0, 0, 0, 0, 0],
           [0, 0, 0, -1, 0, 0, 0, 0],
           [0, 0, 0, 0, 1, 0, 0, 0],
           [0, 0, 0, 0, 0, -1, 0, 0],
           [0, 0, 0, 0, 0, 0, 1, 0],
           [0, 0, 0, 0, 0, 0, 0, -1]])
Isigma_zI= np.array([[1, 0, 0, 0, 0, 0, 0, 0],
           [0, 1, 0, 0, 0, 0, 0, 0],
           [0, 0, -1, 0, 0, 0, 0, 0],
           [0, 0, 0, -1, 0, 0, 0, 0],
           [0, 0, 0, 0, 1, 0, 0, 0],
           [0, 0, 0, 0, 0, 1, 0, 0],
           [0, 0, 0, 0, 0, 0, -1, 0],
           [0, 0, 0, 0, 0, 0, 0, -1]])
sigma_zII= np.array([[1, 0, 0, 0, 0, 0, 0, 0],
           [0, 1, 0, 0, 0, 0, 0, 0],
           [0, 0, 1, 0, 0, 0, 0, 0],
           [0, 0, 0, 1, 0, 0, 0, 0],
           [0, 0, 0, 0, -1, 0, 0, 0],
           [0, 0, 0, 0, 0, -1, 0, 0],
           [0, 0, 0, 0, 0, 0, -1, 0],
           [0, 0, 0, 0, 0, 0, 0, -1]])
sigma_z_z_z= np.array([[1, 0, 0, 0, 0, 0, 0, 0],
           [0, -1, 0, 0, 0, 0, 0, 0],
           [0, 0, -1, 0, 0, 0, 0, 0],
           [0, 0, 0, 1, 0, 0, 0, 0],
           [0, 0, 0, 0, -1, 0, 0, 0],
           [0, 0, 0, 0, 0, 1, 0, 0],
           [0, 0, 0, 0, 0, 0, 1, 0],
           [0, 0, 0, 0, 0, 0, 0, -1]])

IIsigma_x= np.array([[0, 1, 0, 0, 0, 0, 0, 0],
           [1, 0, 0, 0, 0, 0, 0, 0],
           [0, 0, 0, 1, 0, 0, 0, 0],
           [0, 0, 1, 0, 0, 0, 0, 0],
           [0, 0, 0, 0, 0, 1, 0, 0],
           [0, 0, 0, 0, 1, 0, 0, 0],
           [0, 0, 0, 0, 0, 0, 0, 1],
           [0, 0, 0, 0, 0, 0, 1, 0]])


sigma_z_z_I= np.array([[1, 0, 0, 0, 0, 0, 0, 0],
           [0, 1, 0, 0, 0, 0, 0, 0],
           [0, 0, -1, 0, 0, 0, 0, 0],
           [0, 0, 0, -1, 0, 0, 0, 0],
           [0, 0, 0, 0, -1, 0, 0, 0],
           [0, 0, 0, 0, 0, -1, 0, 0],
           [0, 0, 0, 0, 0, 0, 1, 0],
           [0, 0, 0, 0, 0, 0, 0, 1]])

sigma_z_I_z= np.array([[1, 0, 0, 0, 0, 0, 0, 0],
           [0, -1, 0, 0, 0, 0, 0, 0],
           [0, 0, 1, 0, 0, 0, 0, 0],
           [0, 0, 0, -1, 0, 0, 0, 0],
           [0, 0, 0, 0, -1, 0, 0, 0],
           [0, 0, 0, 0, 0, 1, 0, 0],
           [0, 0, 0, 0, 0, 0, -1, 0],
           [0, 0, 0, 0, 0, 0, 0, 1]])
Isigma_x_I=np.array([[0, 0, 1, 0, 0, 0, 0, 0],
           [0, 0, 0, 1, 0, 0, 0, 0],
           [1, 0, 0, 0, 0, 0, 0, 0],
           [0, 1, 0, 0, 0, 0, 0, 0],
           [0, 0, 0, 0, 0, 0, 1, 0],
           [0, 0, 0, 0, 0, 0, 0, 1],
           [0, 0, 0, 0, 1, 0, 0, 0],
           [0, 0, 0, 0, 0, 1, 0, 0]])
sigma_x_I_I=np.array([[0, 0, 0, 0, 1, 0, 0, 0],
           [0, 0, 0, 0, 0, 1, 0, 0],
           [0, 0, 0, 0, 0, 0, 1, 0],
           [0, 0, 0, 0, 0, 0, 0, 1],
           [1, 0, 0, 0, 0, 0, 0, 0],
           [0, 1, 0, 0, 0, 0, 0, 0],
           [0, 0, 1, 0, 0, 0, 0, 0],
           [0, 0, 0, 1, 0, 0, 0, 0]])
IIsigma_y = np.array([[0,  -1.j,  0,  0,  0,  0,  0,  0],
           [1.j,  0,  0,  0,  0,  0,  0,  0],
           [0,  0,  0, -1.j,  0,  0,  0,  0],
           [0,  0, 1.j,  0,  0,  0,  0,  0],
           [0,  0,  0,  0,  0, -1.j,  0,  0],
           [0,  0,  0,  0, 1.j,  0,  0,  0],
           [0,  0,  0,  0,  0,  0,  0, -1.j],
           [0,  0,  0,  0,  0,  0, 1.j,  0]])
sigma_y_I_I = np.array([[0,  0,  0,  0,  -1.j,  0,  0,  0],
           [0,  0,  0,  0,  0, -1.j,  0,  0],
           [0,  0,  0,  0,  0,  0, -1.j,  0],
           [0,  0,  0,  0,  0,  0,  0, -1.j],
           [1.j,  0,  0,  0,  0,  0,  0,  0],
           [0,  1.j,  0,  0,  0,  0,  0,  0],
           [0,  0,  1.j,  0,  0,  0,  0,  0],
           [0,  0,  0, 1.j,  0,  0,  0,  0]])
Isigma_y_I = np.array([[0,  0, -1.j,  0,  0,  0,  0,  0],
           [0,  0,  0, -1.j,  0,  0,  0,  0],
           [1.j,  0,  0,  0,  0,  0,  0,  0],
           [0,  1.j,  0,  0,  0,  0,  0,  0],
           [0,  0,  0,  0,  0,  0, -1.j,  0],
           [0,  0,  0,  0,  0,  0,  0, -1.j],
           [0,  0,   0,  0, 1.j,  0,  0,  0],
           [0,  0,  0,  0,  0, 1.j,  0,  0]])
Isigma_z_z = np.array([[1, 0, 0, 0, 0, 0, 0, 0],
           [0, -1, 0, 0, 0, 0, 0, 0],
           [0, 0, -1, 0, 0, 0, 0, 0],
           [0, 0, 0,  1, 0, 0, 0, 0],
           [0, 0, 0, 0,  1, 0, 0, 0],
           [0, 0, 0, 0, 0, -1, 0, 0],
           [0, 0, 0, 0, 0, 0, -1, 0],
           [0, 0, 0, 0, 0, 0, 0, 1]])


In [ ]:
def guess_control1(t, args , ampl0=0.2):
    return ampl0 * krotov.shapes.flattop(
        t, t_start=0, t_stop=700, t_rise=0.3, func="blackman"
    )

def guess_control2(t, args , ampl0=0.2):
    return ampl0 * krotov.shapes.flattop(
        t, t_start=0, t_stop=700, t_rise=0.3, func="blackman"
    )

def guess_control3(t, args , ampl0=0.2):
    return ampl0 * krotov.shapes.flattop(
        t, t_start=0, t_stop=700, t_rise=0.3, func="blackman"
    )
def guess_control4(t, args , ampl0=0.2):
    return ampl0 * krotov.shapes.flattop(
        t, t_start=0, t_stop=700, t_rise=0.3, func="blackman"
    )
def guess_control5(t, args , ampl0=0.2):
    return ampl0 * krotov.shapes.flattop(
        t, t_start=0, t_stop=700, t_rise=0.3, func="blackman"
    )
def guess_control6(t, args , ampl0=0.2):
    return ampl0 * krotov.shapes.flattop(
        t, t_start=0, t_stop=700, t_rise=0.3, func="blackman"
    )

In [ ]:
def hamiltonian(omega1=1 ,omega2=3, omega3=2, ampl0=0.2, J1=0.047, J2=0.097, J3= 0.028  ):
    H0 = qutip.Qobj((-0.5) *( omega1 * sigma_zII +  omega2 * Isigma_zI + omega3 * IIsigma_z)+ J1* (Isigma_z_z) + J2*(sigma_z_I_z) + J3*(sigma_z_z_I))
    H1 = qutip.Qobj(IIsigma_x)
    H2 = qutip.Qobj(Isigma_x_I)
    H3 = qutip.Qobj(sigma_x_I_I)
    H4 = qutip.Qobj(IIsigma_y)
    H5 = qutip.Qobj(Isigma_y_I)
    H6 = qutip.Qobj(sigma_y_I_I)

    return [H0,[H1,guess_control1],[H2,guess_control2],[H3,guess_control3],[H4,guess_control4],[H5,guess_control5],[H6,guess_control6]]


H = hamiltonian()

In [ ]:
H

[Quantum object: dims = [[8], [8]], shape = (8, 8), type = oper, isherm = True
 Qobj data =
 [[-2.828  0.     0.     0.     0.     0.     0.     0.   ]
  [ 0.    -1.116  0.     0.     0.     0.     0.     0.   ]
  [ 0.     0.     0.022  0.     0.     0.     0.     0.   ]
  [ 0.     0.     0.     1.922  0.     0.     0.     0.   ]
  [ 0.     0.     0.     0.    -2.078  0.     0.     0.   ]
  [ 0.     0.     0.     0.     0.     0.022  0.     0.   ]
  [ 0.     0.     0.     0.     0.     0.     0.884  0.   ]
  [ 0.     0.     0.     0.     0.     0.     0.     3.172]],
 [Quantum object: dims = [[8], [8]], shape = (8, 8), type = oper, isherm = True
  Qobj data =
  [[0. 1. 0. 0. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 1. 0. 0. 0. 0.]
   [0. 0. 1. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 1. 0. 0.]
   [0. 0. 0. 0. 1. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 1.]
   [0. 0. 0. 0. 0. 0. 1. 0.]],
  <function __main__.guess_control1(t, args, ampl0=0.2)>],
 [Quantum object: dims = [[8], [8]], sh

In [ ]:
tlist = np.linspace(0, 700, 7000)

In [ ]:
def logical_basis(H):
    H0 = qutip.Qobj((-0.5) *( 1 * IIsigma_z +  3 * Isigma_zI + 2 * sigma_zII))
    eigenvals, eigenvecs = scipy.linalg.eig(H0.full())
    ndx = np.argsort(eigenvals.real)
    E = eigenvals[ndx].real
    V = eigenvecs[:, ndx]
    psi000 = qutip.Qobj(V[:, 0])
    psi001 = qutip.Qobj(V[:, 1])
    psi010 = qutip.Qobj(V[:, 2])
    psi011 = qutip.Qobj(V[:, 3])
    psi100 = qutip.Qobj(V[:, 4])
    psi101 = qutip.Qobj(V[:, 5])
    psi110 = qutip.Qobj(V[:, 6])
    psi111 = qutip.Qobj(V[:, 7])
    w01 = E[1] - E[0]  # Transition energy between states
    print("Energy of qubit transition is %.3f" % w01)
    return psi000, psi001, psi010, psi011, psi100, psi101, psi110, psi111

psi000, psi001, psi010, psi011, psi100, psi101, psi110, psi111 = logical_basis(H)

Energy of qubit transition is 1.000


In [ ]:
proj000 = qutip.ket2dm(psi000)
proj001 = qutip.ket2dm(psi001)
proj010 = qutip.ket2dm(psi010)
proj011 = qutip.ket2dm(psi011)
proj100 = qutip.ket2dm(psi100)
proj101 = qutip.ket2dm(psi101)
proj110 = qutip.ket2dm(psi110)
proj111 = qutip.ket2dm(psi111)

In [ ]:
basis = [psi000, psi001, psi010, psi011, psi100, psi101, psi110, psi111]
basis

[Quantum object: dims = [[8], [1]], shape = (8, 1), type = ket
 Qobj data =
 [[1.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]],
 Quantum object: dims = [[8], [1]], shape = (8, 1), type = ket
 Qobj data =
 [[0.]
  [1.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]],
 Quantum object: dims = [[8], [1]], shape = (8, 1), type = ket
 Qobj data =
 [[0.]
  [0.]
  [0.]
  [0.]
  [1.]
  [0.]
  [0.]
  [0.]],
 Quantum object: dims = [[8], [1]], shape = (8, 1), type = ket
 Qobj data =
 [[0.]
  [0.]
  [1.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]],
 Quantum object: dims = [[8], [1]], shape = (8, 1), type = ket
 Qobj data =
 [[0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [1.]
  [0.]
  [0.]],
 Quantum object: dims = [[8], [1]], shape = (8, 1), type = ket
 Qobj data =
 [[0.]
  [0.]
  [0.]
  [1.]
  [0.]
  [0.]
  [0.]
  [0.]],
 Quantum object: dims = [[8], [1]], shape = (8, 1), type = ket
 Qobj data =
 [[0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [1.]
  [0.]],
 Quantum object: dims = [[8], [1]], shape = (8, 1), type = ket

In [ ]:

objectives=[0]*100
for i in range(100):
  objectives[i] = krotov.gate_objectives(
      basis_states=[psi000, psi001, psi010, psi011, psi100, psi101, psi110, psi111], gate=RandU_3Q[i], H=H
  )



def S(t):
    """Scales the Krotov methods update of the pulse value at the time t"""
    return krotov.shapes.flattop(
        t, t_start=0, t_stop=700, t_rise=0.3, t_fall=0.3, func='blackman'
   )


pulse_options = {
    H[1][1]: dict(lambda_a=1, update_shape=S),
    H[2][1]: dict(lambda_a=1, update_shape=S),
    H[3][1]: dict(lambda_a=1, update_shape=S),
    H[4][1]: dict(lambda_a=1, update_shape=S),
    H[5][1]: dict(lambda_a=1, update_shape=S),
    H[6][1]: dict(lambda_a=1, update_shape=S)
}

In [ ]:
results=[]
for i in range(2):

  opt_result = krotov.optimize_pulses(
      objectives[i],
      pulse_options=pulse_options,
      tlist=tlist,
      propagator=krotov.propagators.expm,
      chi_constructor=krotov.functionals.chis_sm,
      info_hook=krotov.info_hooks.print_table(J_T=krotov.functionals.J_T_sm),
      check_convergence=krotov.convergence.Or(
          krotov.convergence.value_below('1e-3', name='J_T'),
          krotov.convergence.delta_below(1e-5),
          krotov.convergence.check_monotonic_error,
      ),
      store_all_pulses=True,
  )

  results.append(opt_result)


  #j_f=[]
  #j_f.append(opt_result.info_vals)
#print(j_f)


iter.      J_T   ∑∫gₐ(t)dt          J       ΔJ_T         ΔJ  secs
0     9.59e-01    0.00e+00   9.59e-01        n/a        n/a   371
1     3.66e-01    1.09e-01   4.75e-01  -5.93e-01  -4.84e-01   703
2     3.19e-02    1.50e-01   1.82e-01  -3.34e-01  -1.84e-01   689
3     5.39e-03    1.33e-02   1.87e-02  -2.65e-02  -1.33e-02   701
4     1.49e-03    1.97e-03   3.46e-03  -3.90e-03  -1.93e-03   793
5     7.27e-04    3.85e-04   1.11e-03  -7.62e-04  -3.77e-04   671
iter.      J_T   ∑∫gₐ(t)dt          J       ΔJ_T         ΔJ  secs
0     8.98e-01    0.00e+00   8.98e-01        n/a        n/a   412
1     5.32e-02    2.08e-01   2.61e-01  -8.45e-01  -6.38e-01   780
2     1.80e-02    1.76e-02   3.56e-02  -3.52e-02  -1.76e-02   606
3     1.07e-02    3.70e-03   1.43e-02  -7.36e-03  -3.66e-03   745
4     6.98e-03    1.85e-03   8.82e-03  -3.67e-03  -1.83e-03   817
5     4.73e-03    1.13e-03   5.86e-03  -2.25e-03  -1.12e-03   657
6     3.28e-03    7.27e-04   4.01e-03  -1.45e-03  -7.19e-04   721
7     2.36

In [ ]:
results[0]

Krotov Optimization Result
--------------------------
- Started at 2023-06-09 11:10:01
- Number of objectives: 8
- Number of iterations: 5
- Reason for termination: Reached convergence: J_T < 1e-3
- Ended at 2023-06-09 12:15:32 (1:05:31)

In [ ]:
results[1]

Krotov Optimization Result
--------------------------
- Started at 2023-06-09 12:15:32
- Number of objectives: 8
- Number of iterations: 11
- Reason for termination: Reached convergence: J_T < 1e-3
- Ended at 2023-06-09 14:30:10 (2:14:38)

In [ ]:
J_F_3Q_J2_6K1=[]
for i in range(2):
  J_F_3Q_J2_6K1.append(results[i].info_vals)

In [ ]:
results2=[]
for i in range(2, 4):

  opt_result = krotov.optimize_pulses(
      objectives[i],
      pulse_options=pulse_options,
      tlist=tlist,
      propagator=krotov.propagators.expm,
      chi_constructor=krotov.functionals.chis_sm,
      info_hook=krotov.info_hooks.print_table(J_T=krotov.functionals.J_T_sm),
      check_convergence=krotov.convergence.Or(
          krotov.convergence.value_below('1e-3', name='J_T'),
          krotov.convergence.delta_below(1e-5),
          krotov.convergence.check_monotonic_error,
      ),
      store_all_pulses=True,
  )

  results2.append(opt_result)


  #j_f=[]
  #j_f.append(opt_result.info_vals)
#print(j_f)


iter.      J_T   ∑∫gₐ(t)dt          J       ΔJ_T         ΔJ  secs
0     9.65e-01    0.00e+00   9.65e-01        n/a        n/a   398
1     5.70e-01    8.45e-02   6.54e-01  -3.95e-01  -3.11e-01   762
2     2.22e-01    1.49e-01   3.72e-01  -3.47e-01  -1.98e-01   650
3     1.07e-01    5.60e-02   1.63e-01  -1.15e-01  -5.94e-02   610
4     5.91e-02    2.38e-02   8.29e-02  -4.80e-02  -2.42e-02   769
5     3.24e-02    1.34e-02   4.57e-02  -2.67e-02  -1.34e-02   733
6     1.84e-02    6.97e-03   2.54e-02  -1.39e-02  -6.95e-03   628
7     1.11e-02    3.66e-03   1.48e-02  -7.29e-03  -3.63e-03   625
8     7.08e-03    2.05e-03   9.12e-03  -4.07e-03  -2.03e-03   614
9     4.73e-03    1.18e-03   5.91e-03  -2.35e-03  -1.17e-03   724
10    3.30e-03    7.20e-04   4.02e-03  -1.43e-03  -7.09e-04   647
11    2.40e-03    4.57e-04   2.85e-03  -9.05e-04  -4.49e-04   689
12    1.78e-03    3.09e-04   2.09e-03  -6.13e-04  -3.04e-04   639
14    1.03e-03    1.60e-04   1.19e-03  -3.16e-04  -1.57e-04   588
15    7.97

In [ ]:
results2[0]

Krotov Optimization Result
--------------------------
- Started at 2023-06-09 14:32:28
- Number of objectives: 8
- Number of iterations: 15
- Reason for termination: Reached convergence: J_T < 1e-3
- Ended at 2023-06-09 17:27:19 (2:54:51)

In [ ]:
results2[0]

Krotov Optimization Result
--------------------------
- Started at 2023-06-09 14:32:28
- Number of objectives: 8
- Number of iterations: 15
- Reason for termination: Reached convergence: J_T < 1e-3
- Ended at 2023-06-09 17:27:19 (2:54:51)

In [ ]:
J_F_3Q_J2_6K2=[]
for i in range(2):
  J_F_3Q_J2_6K2.append(results2[i].info_vals)

In [ ]:
results3=[]
for i in range(4, 6):

  opt_result = krotov.optimize_pulses(
      objectives[i],
      pulse_options=pulse_options,
      tlist=tlist,
      propagator=krotov.propagators.expm,
      chi_constructor=krotov.functionals.chis_sm,
      info_hook=krotov.info_hooks.print_table(J_T=krotov.functionals.J_T_sm),
      check_convergence=krotov.convergence.Or(
          krotov.convergence.value_below('1e-3', name='J_T'),
          krotov.convergence.delta_below(1e-5),
          krotov.convergence.check_monotonic_error,
      ),
      store_all_pulses=True,
  )

  results3.append(opt_result)


  #j_f=[]
  #j_f.append(opt_result.info_vals)
#print(j_f)


iter.      J_T   ∑∫gₐ(t)dt          J       ΔJ_T         ΔJ  secs
0     9.98e-01    0.00e+00   9.98e-01        n/a        n/a   328
1     6.17e-01    2.31e-02   6.40e-01  -3.82e-01  -3.59e-01   659
2     1.41e-01    1.89e-01   3.30e-01  -4.76e-01  -2.87e-01   694
3     2.96e-02    5.42e-02   8.38e-02  -1.11e-01  -5.69e-02   710
4     9.98e-03    9.85e-03   1.98e-02  -1.97e-02  -9.81e-03   765
5     3.84e-03    3.08e-03   6.92e-03  -6.13e-03  -3.05e-03   899
6     1.53e-03    1.16e-03   2.69e-03  -2.31e-03  -1.15e-03   665
7     7.06e-04    4.15e-04   1.12e-03  -8.27e-04  -4.12e-04   799
iter.      J_T   ∑∫gₐ(t)dt          J       ΔJ_T         ΔJ  secs
0     9.63e-01    0.00e+00   9.63e-01        n/a        n/a   413
1     4.20e-01    1.08e-01   5.28e-01  -5.43e-01  -4.35e-01   696
2     9.11e-02    1.46e-01   2.37e-01  -3.29e-01  -1.83e-01   644
3     9.45e-03    4.01e-02   4.95e-02  -8.17e-02  -4.16e-02   609
4     2.84e-03    3.32e-03   6.16e-03  -6.61e-03  -3.29e-03   887
5     1.14

In [ ]:
results3[0]

Krotov Optimization Result
--------------------------
- Started at 2023-06-09 19:11:18
- Number of objectives: 8
- Number of iterations: 7
- Reason for termination: Reached convergence: J_T < 1e-3
- Ended at 2023-06-09 20:43:22 (1:32:04)

In [ ]:
results3[1]

Krotov Optimization Result
--------------------------
- Started at 2023-06-09 20:43:23
- Number of objectives: 8
- Number of iterations: 6
- Reason for termination: Reached convergence: J_T < 1e-3
- Ended at 2023-06-09 21:59:01 (1:15:38)

In [ ]:
J_F_3Q_J2_6K3=[]
for i in range(2):
  J_F_3Q_J2_6K3.append(results3[i].info_vals)

In [ ]:
results4=[]
for i in range(6, 8):

  opt_result = krotov.optimize_pulses(
      objectives[i],
      pulse_options=pulse_options,
      tlist=tlist,
      propagator=krotov.propagators.expm,
      chi_constructor=krotov.functionals.chis_sm,
      info_hook=krotov.info_hooks.print_table(J_T=krotov.functionals.J_T_sm),
      check_convergence=krotov.convergence.Or(
          krotov.convergence.value_below('1e-3', name='J_T'),
          krotov.convergence.delta_below(1e-5),
          krotov.convergence.check_monotonic_error,
      ),
      store_all_pulses=True,
  )

  results4.append(opt_result)


  #j_f=[]
  #j_f.append(opt_result.info_vals)
#print(j_f)


iter.      J_T   ∑∫gₐ(t)dt          J       ΔJ_T         ΔJ  secs
0     9.85e-01    0.00e+00   9.85e-01        n/a        n/a   291
1     4.21e-01    7.62e-02   4.97e-01  -5.64e-01  -4.88e-01   684
2     1.28e-01    1.30e-01   2.58e-01  -2.93e-01  -1.63e-01   613
3     4.85e-02    3.91e-02   8.76e-02  -7.94e-02  -4.03e-02   671
4     2.60e-02    1.12e-02   3.73e-02  -2.24e-02  -1.12e-02   719
5     1.54e-02    5.33e-03   2.08e-02  -1.06e-02  -5.27e-03   840
6     1.01e-02    2.70e-03   1.28e-02  -5.36e-03  -2.66e-03   775
7     7.13e-03    1.49e-03   8.61e-03  -2.95e-03  -1.47e-03   800
8     5.34e-03    9.01e-04   6.24e-03  -1.79e-03  -8.88e-04   788
9     4.12e-03    6.16e-04   4.73e-03  -1.22e-03  -6.06e-04   797
10    3.21e-03    4.55e-04   3.67e-03  -9.02e-04  -4.47e-04   820
11    2.52e-03    3.49e-04   2.87e-03  -6.92e-04  -3.43e-04   809
12    1.98e-03    2.73e-04   2.25e-03  -5.42e-04  -2.68e-04   697
13    1.55e-03    2.15e-04   1.77e-03  -4.27e-04  -2.12e-04   777
14    1.22

In [ ]:
results4[0]

Krotov Optimization Result
--------------------------
- Started at 2023-06-10 03:18:20
- Number of objectives: 8
- Number of iterations: 15
- Reason for termination: Reached convergence: J_T < 1e-3
- Ended at 2023-06-10 06:28:26 (3:10:06)

In [ ]:
results4[1]

Krotov Optimization Result
--------------------------
- Started at 2023-06-10 06:28:26
- Number of objectives: 8
- Number of iterations: 6
- Reason for termination: Reached convergence: J_T < 1e-3
- Ended at 2023-06-10 07:42:14 (1:13:48)

In [ ]:
J_F_3Q_J2_6K4=[]
for i in range(2):
  J_F_3Q_J2_6K4.append(results4[i].info_vals)

In [ ]:
results5=[]
for i in range(8, 10):

  opt_result = krotov.optimize_pulses(
      objectives[i],
      pulse_options=pulse_options,
      tlist=tlist,
      propagator=krotov.propagators.expm,
      chi_constructor=krotov.functionals.chis_sm,
      info_hook=krotov.info_hooks.print_table(J_T=krotov.functionals.J_T_sm),
      check_convergence=krotov.convergence.Or(
          krotov.convergence.value_below('1e-3', name='J_T'),
          krotov.convergence.delta_below(1e-5),
          krotov.convergence.check_monotonic_error,
      ),
      store_all_pulses=True,
  )

  results5.append(opt_result)


  #j_f=[]
  #j_f.append(opt_result.info_vals)
#print(j_f)


iter.      J_T   ∑∫gₐ(t)dt          J       ΔJ_T         ΔJ  secs
0     9.70e-01    0.00e+00   9.70e-01        n/a        n/a   353
1     4.22e-01    9.54e-02   5.17e-01  -5.48e-01  -4.52e-01   624
2     7.16e-02    1.54e-01   2.26e-01  -3.50e-01  -1.96e-01   656
3     9.38e-03    3.07e-02   4.01e-02  -6.22e-02  -3.15e-02   732
4     2.81e-03    3.31e-03   6.12e-03  -6.56e-03  -3.25e-03   599
5     1.11e-03    8.56e-04   1.97e-03  -1.70e-03  -8.41e-04   705
6     5.94e-04    2.63e-04   8.57e-04  -5.20e-04  -2.57e-04   755
iter.      J_T   ∑∫gₐ(t)dt          J       ΔJ_T         ΔJ  secs
0     9.55e-01    0.00e+00   9.55e-01        n/a        n/a   283
1     3.73e-01    1.23e-01   4.95e-01  -5.83e-01  -4.60e-01   613
2     1.13e-01    1.19e-01   2.33e-01  -2.59e-01  -1.40e-01   597
3     2.66e-02    4.25e-02   6.91e-02  -8.68e-02  -4.43e-02   625
4     8.35e-03    9.09e-03   1.74e-02  -1.82e-02  -9.11e-03   644
5     3.36e-03    2.51e-03   5.87e-03  -4.99e-03  -2.49e-03   698
6     1.62

In [ ]:
results5[0]

Krotov Optimization Result
--------------------------
- Started at 2023-06-10 08:28:39
- Number of objectives: 8
- Number of iterations: 6
- Reason for termination: Reached convergence: J_T < 1e-3
- Ended at 2023-06-10 09:42:27 (1:13:48)

In [ ]:
results5[1]

Krotov Optimization Result
--------------------------
- Started at 2023-06-10 09:42:27
- Number of objectives: 8
- Number of iterations: 7
- Reason for termination: Reached convergence: J_T < 1e-3
- Ended at 2023-06-10 11:07:54 (1:25:27)

In [ ]:
J_F_3Q_J2_6K5=[]
for i in range(2):
  J_F_3Q_J2_6K5.append(results5[i].info_vals)